version: '3'
services:
  lend-guard-oracle:
    image: node:20.9.0
    container_name: lend-guard-oracle
    working_dir: /usr/src/app
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/index.js:/usr/src/app/index.js
      - ./app/package.json:/usr/src/app/package.json
      - ./app/package-lock.json:/usr/src/app/package-lock.json
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: sh -c "npm install && npm start"
    networks:
      - oracle_network
    restart: unless-stopped

  oracle-redis:
    image: "redis:7.2"
    container_name: oracle-redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    networks:
      - oracle_network

networks:
  oracle_network:
    driver: bridge

volumes:
  redis_data:
